# Generated by Django 3.0.2 on 2020-01-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='admn_no',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('issued_date', models.DateField()),
                ('is_issued', models.BooleanField()),
                ('issued_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.UserInfo', to_field='admn_no')),
            ],
        ),
    ]
