# Generated by Django 3.0.2 on 2020-01-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200112_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='issued_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserInfo', to_field='admn_no'),
        ),
    ]
